title: Lyndsey Ferguson
description: Software Engineer · Plugin Author · CI/CD Leader
url: "https://lyndseyferguson.info"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Minimal Mistakes settings
minimal_mistakes_skin: "default"
markdown: kramdown
highlighter: rouge
