title: "Lyndsey Ferguson"
email: ""
description: >-
  Helping teams scale through automation, clarity, and engineering leadership.
baseurl: ""
url: "https://lyndseyferguson.info"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
