title: Lyndsey Ferguson
description: Software Engineer · Plugin Author · CI/CD Leader
url: "https://lyndseyferguson.info"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Minimal Mistakes settings
minimal_mistakes_skin: "default"
markdown: kramdown
highlighter: rouge
